### ISSUE TITLE
Kamerabewegung mit Arm synchronisieren

### ISSUE THREAD

**Issue by peli0451** [peli0451/arcactus#1]
Aktuell kann zwar die Blickrichtung beliebig geändert werden, die Schüsse werden aber alle auf derselben Höhe abgefeuert.
Der PlayerController muss so abgeändert werden, dass sich der Arm und damit der Spawnpoint für die Dornen mit der Kamerablickrichtung mitbewegt.

**Comment by miccl** [comment]
Innerhalb der Unity Samples ist ein Beispiel dafür.

**Comment by miccl** [comment]
Done. Durch Verschieben des Armes in CenterEyeAnchor.
