### ISSUE TITLE
HUD-Elemente werden mit angeschlossener Oculus nicht angezeigt.

### ISSUE THREAD

**Issue by miccl** [peli0451/arcactus#19]

**Comment by peli0451** [comment]
Wenn der Render-Mode des Canvas auf "Screen Space - Overlay" steht, verschwindet das HUD ingame. Es gibt einen (hässlichen) Workaround durch Setzen auf World Space mit sehr niedriger Entfernung zur Kamera. Suchen noch etwas besseres.

**Comment by miccl** [comment]
Oculus unterstützt Screen Space - Overlay nicht ([siehe](http://forum.unity3d.com/threads/unity-5-1-vr-getting-started.332316/)).
Haben erstmal (hässlichen !) Workaround verwendet. 
Bei VR kann die  HUD nicht wohl nicht so gut dargestellt werden kann, da durch die Tiefenwirkung/Steoreoskopie die HUD-Objekte schlechte dargestellt werden und manchmal doppelt vorkommen. ([siehe](http://media.steampowered.com/apps/valve/2013/Team_Fortress_in_VR_GDC.pdf))
Deshalb voerst geschlossen.
