### ISSUE TITLE
Punkteanzeige dynamisch über Gegnern

### ISSUE THREAD

**Issue by peli0451** [peli0451/arcactus#22]

**Comment by miccl** [comment]
- http://forum.unity3d.com/threads/show-a-text-damage-after-the-monster-is-hit.281697/
- http://answers.unity3d.com/questions/718449/pop-up-guitext-after-enemies-destroyed.html
- http://answers.unity3d.com/questions/1009973/item-name-uigui-text-over-itemenemy-in-3d.html
- http://forum.unity3d.com/threads/floating-text-over-a-gameobject.323709/
- https://www.reddit.com/r/Unity3D/comments/34b5y1/how_to_keep_a_ui_element_positioned_above_a_game/
- http://answers.unity3d.com/questions/47300/dynamic-text-on-object.html

**Comment by miccl** [comment]
Resolved in dd77e74
