### ISSUE TITLE
Zielverhalten festlegen und implementieren

### ISSUE THREAD

**Issue by peli0451** [peli0451/arcactus#24]
Aktuell schießt man nicht genau dorthin wo der Marker ist.
Vermutlich so: separater Collider (unsichtbar), der aus Kameramitte abgefeuert wird.

**Comment by miccl** [comment]
- https://www.youtube.com/watch?v=mpxim8YbsMk

**Comment by miccl** [comment]
Closed in commit 56a7d81 by adding raycasting shooting
