### ISSUE TITLE
Verwendete Oculus-Utilities aufräumen

### ISSUE THREAD

**Issue by peli0451** [peli0451/arcactus#25]
Nur das übrig lassen, was gebraucht wird.

**Comment by miccl** [comment]
Alles klare rausgeräumt, geht bestimmt mehr. Jedoch ist sowas wie global_menu zu löschen gefährlich^^ Mit der Oculus könnte dann ja auf einmal nen Menü benötigt werden. Und lieber mehr drinne lassen als zu viel rausnehmen (was häufig passiert ist).
