### ISSUE TITLE
Feedback bei Hit

### ISSUE THREAD

**Issue by peli0451** [peli0451/arcactus#29]
Der Spieler sollte es irgendwie merken, dass er getroffen wurde, unabhängig vom abgezogenen Leben.
Möglichkeiten:
- Kamera ruckelt (blöd)
- Bildschirm wird kurz rötlich
  ggf. kombiniert.

**Comment by miccl** [comment]
- http://answers.unity3d.com/questions/31193/screen-flashes-red-when-taking-damage.html
- http://answers.unity3d.com/questions/25177/shoot-the-player-effect.html

**Comment by miccl** [comment]
Resolved in commit 0a4220e by adding [ScreenFlash.cs](https://github.com/peli0451/arcactus/blob/0a4220e289fb59325a90acd9c7e8d41a3f6b7ba6/Arcactus/Assets/ScreenFlash.cs)  to the main camera and instatiate it in the playerController.
