### ISSUE TITLE
Power-Up-Funktionalität

### ISSUE THREAD

**Issue by peli0451** [peli0451/arcactus#30]
Für die einzelnen Power-Up- und Power-Down-Typen:
- Einbinden und Spawnenlassen des Prefabs
- Aktivierung der Power-Ups / -Downs mit entsprechender Wirkung (bei sofort wirkenden)
- Einsammeln und mögliche Aktivierung bei manuell zu aktivierenden
- Fallen irgendwie von oben runter.

**Comment by peli0451** [comment]
Fallen irgendwie von oben runter.

**Comment by miccl** [comment]
Soweit implementiert.
Einzig die Spawnlogik, wo, wann und wie wahrscheinlich sie spawnen ist nicht definiert.
Ebenso fehlt die Implementierung einiger Effekte. Jedoch das Prefab steht erstmal.

**Comment by miccl** [comment]
Fehlende PowerUp-Typen:
- Mehrfachschuss
- Fön

**Comment by miccl** [comment]
Vorläufig wird das Issue geschlossen.
Zufällige Spawn Logik ist jetzt implementiert, indem die verschiedenen mit gleicher Wkt. gewählt werden (a7a0e95)
Fehlen tuen nur noch die fortgeschritteren PowerUps:
- Fön
- Mehrfachschuss
- AoE-Schuss
