### ISSUE TITLE
Gelände bauen

### ISSUE THREAD

**Issue by miccl** [peli0451/arcactus#36]
- ~~Berge im Hintergrund~~ (cf. #54)
- ~~Steine auf dem Boden~~ (cf. #55)
- ~~Dünen~~ (cf. 191646196af8b1b9d77e00de5d35062fee052cae)
- ~~Sandtextur~~ (cf. 191646196af8b1b9d77e00de5d35062fee052cae)
- ~~Lichteinstellungen~~ (cf. 216c3b2bba31263d6f56934e470527d0d323f5f3)

**Comment by peli0451** [comment]
Anmerkung zum Licht: Der Arm wirft einen Schatten. Das sieht etwas komisch aus, da wir keinen Körper haben.

**Comment by peli0451** [comment]
Guidelines hier, aber speziell zu Fadenkreuzen gibt es da nichts...
https://developer.oculus.com/documentation/intro-vr/latest/concepts/bp_app_ui/

**Comment by peli0451** [comment]
Wurde zum Teil behoben, der Rest wurde in neue Issues migriert.
Oben kenntlich gemacht.
