### ISSUE TITLE
Credits

### ISSUE THREAD

**Issue by peli0451** [peli0451/arcactus#46]

**Comment by miccl** [comment]
Sounds:
- Balloon Bounce: https://www.freesound.org/people/wuola/sounds/168300/
- Balloon Pop: https://www.freesound.org/people/Mart1001/sounds/54012/
- Shoot: http://www.freesound.org/people/ani_music/sounds/244978/
- PowerUp Pop: http://www.freesound.org/people/distillerystudio/sounds/327736/
- Hintergrundmusik: "River Valley Breakdown" Kevin MacLeod (incompetech.com) 
  Licensed under Creative Commons: By Attribution 3.0
  http://creativecommons.org/licenses/by/3.0/

Quelle:
- Menu-Auswahl: http://talesfromtherift.com/vr-gaze-input/
- Crosshair-Implementierung: https://www.youtube.com/watch?v=LLKYbwNnKDg
-
