### ISSUE TITLE
Punktgewinnanzeige bei Gegner 

### ISSUE THREAD

**Issue by miccl** [peli0451/arcactus#47]
Anzeige soll dynamisch initialisiert werden. Ähnlich wie bei Thorn mithilfe eines Prefabs und SpawnPoints.

**Comment by peli0451** [comment]
Umrandung geht leicht (UI -> Effects -> Outline), aber weil bei blau und rot die Schrift selbst schon recht dunkel ist, hat man nicht viel davon.
Vielleicht könnte man die Schriftfarbe bei blau und rot heller machen (also nicht direkt vom Material, sondern Materialfarbe \* .5 oder so etwas in der Art).
