### ISSUE TITLE
Bugs / TODOs Präsentation

### ISSUE THREAD

**Issue by miccl** [peli0451/arcactus#49]
- ~~Kamerawinkel runter~~ (auf 135°)
- ~~kein bewegen durch controller~~
- ~~berge nicht zu sehen~~ (won't fix - cf. #54)
- ~~crosshair anpassen (oculus guidelines)~~ (#53)

**Comment by miccl** [comment]
- ~~geschwindigkeit der thorns anpassen~~ (migriert nach #61)
- ~~game Over länger anzeigen~~ (solange bis es neugestartet wird)
- ~~Power up Text länger anzeigen~~ (von 1 Sekunde zu 3 geändert) 
- ~~ruckelt bei zu vielen ballons~~ (#50)
- ~~Start to play Text~~ (Durch Menü gelöst)

**Comment by miccl** [comment]
- ~~Raycast dicker~~ (mittels SphereCast statt Raycast und bisher einem Radius von 0.25, muss man mal testen, ob das zu groß ist)

**Comment by peli0451** [comment]
Inzwischen ist alles gefixt oder wird anders gelöst.
Das einzige verbliebene ist jetzt ein eigener Issue: #61
