### ISSUE TITLE
Performance-Probleme

### ISSUE THREAD

**Issue by peli0451** [peli0451/arcactus#50]
Mag z. T. an meinem schlechten Rechner liegen, aber irgendwas zieht die Leistung ziemlich runter. Terrain hat vielleicht Auswirkungen, aber auch mit komplett flachem Terrain hatte ich nur 40 fps bei Start, bei ersten Ballons 20 und als die erste Wave komplett kam, waren es nur noch ca. 10 fps.
Bitte Benchmarks ergänzen.

**Comment by miccl** [comment]
Was soll bei ergänzt werden? Benchmarks ?

**Comment by miccl** [comment]
wahrscheinlich wegen zu großer Terrain und den Bergen
