### ISSUE TITLE
Freeze bei Aktivierung zweier Power-Ups

### ISSUE THREAD

**Issue by peli0451** [peli0451/arcactus#59]
Situation war:
- 2 Power-Ups spawnen kurz hintereinander
- Abschießen des ersten -> Effekt aktiviert
- gleich darauf Abschießen des zweiten -> Freeze
  Freeze war komplett, also es musste sogar der Unity-Prozess gekillt werden.

**Comment by miccl** [comment]
Konntest du das nochmal reproduzieren?

**Comment by peli0451** [comment]
Ja, gleiche Situation, gleicher Effekt.
