### ISSUE TITLE
Oculus-Test

### ISSUE THREAD

**Issue by peli0451** [peli0451/arcactus#7]
Oculus anschließen und ingame verwenden. Sicherstellen, dass die stereoskopische Ansicht und die Inputerkennung wie gewünscht funktionieren.

**Comment by peli0451** [comment]
Ich kann es leider nicht testen. Also die Teile sind alle da und ich hab auch alles angeschlossen, aber anscheinend erfülle ich nicht die Requirements und deshalb geht sie nicht an. Muss also bei jemand anders getestet werden.

siehe:
- https://support.oculus.com/hc/en-us/articles/201835987-Oculus-Rift-Development-Kit-2-FAQ
- https://forums.oculus.com/viewtopic.php?t=27159

**Comment by miccl** [comment]
Oculus wurde erfolgreich getestet. Spielfunktionen funktionieren mit Ausnahme der Anzeige von den HUD-Elementen und dem Stereoscopic-View
